; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s2]
platform = espressif32
board = lolin_s2_mini
framework = arduino
lib_deps = 
	gyverlibs/GyverMenu
	gyverlibs/GyverOLED
	gyverlibs/StringN
build_flags = 
	-Isrc
	-DCFG_TUSB_CONFIG_FILE=\"tusb_config.h\"
	-DFLIP_DISPLAY
	-DDEBUG
	
upload_speed = 921600
monitor_speed = 115200
upload_port = COM6
monitor_port = COM8
